# Copyright (c) 2021 Oracle and/or its affiliates,  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

version: v1
kind: Test
provider: oci
OciTests:

  #Network..
  vcn:
    output: oci_network
    terra_checks:
      display_name: "apache_vcn"
      dns_label : "vcn"
      state: "AVAILABLE"
      cidr_block: "10.0.0.0/16"
  igw:
    output: oci_network
    terra_checks:
      state: "AVAILABLE"
  natgw:
    output: oci_network
    terra_checks:
      state: "AVAILABLE"

  #Subnets..
  bastion:
    output: oci_subnets
    terra_checks:
      display_name: "bastion"
      state: "AVAILABLE"
      cidr_block: "10.0.2.0/24"
  private:
    output: oci_subnets
    terra_checks:
      display_name: "private"
      state: "AVAILABLE"
      cidr_block: "10.0.1.0/24"
  public:
    output: oci_subnets
    terra_checks:
      display_name: "public"
      state: "AVAILABLE"
      cidr_block: "10.0.0.0/24"

  #Compute Instance tests..
  apache_http_server1:
    output: oci_instances
    terra_checks:
      state: "RUNNING"
      shape: "VM.Standard2.2"
    generic_checks:
      file_exists_test_private:
        args:
          public_ip: "output.oci_instances.bastion_inst.public_ip"
          private_ip: "output.private_ip"
          file_name: "/etc/nfs.conf,/etc/nfs1.conf"  
          user_name: "opc"
          private_key: "env.TF_VAR_private_key"
          public_key: "env.TF_VAR_public_key"
      process_running_test_private:
        args:
          public_ip: "output.oci_instances.bastion_inst.public_ip"
          private_ip: "output.private_ip"
          user_name: "opc"
          process_name: "httpd,nginx"
          private_key: "env.TF_VAR_private_key"
          public_key: "env.TF_VAR_public_key"
      ssh_test_private:
        args:
          public_ip: "output.oci_instances.bastion_inst.public_ip"
          private_ip: "output.private_ip"
          user_name: "opc"
          private_key: "env.TF_VAR_private_key"
          public_key: "env.TF_VAR_public_key"

  apache_http_server2:
    output: oci_instances  
    terra_checks:
      state: "RUNNING"
  apache_http_server3:
    output: oci_instances
    terra_checks:
      state: "RUNNING"
      shape: "VM.Standard2.2"   

  bastion_inst:
    output: oci_instances
    terra_checks:
      display_name: "bastion_inst"
      state: "RUNNING"
    generic_checks:
      netcat_test_public:
        args:
          public_ip: "output.public_ip"
          port_open: "22,22"
          port_not_open: "80,8080"
      ssh_test_public:
        args:
          public_ip: "output.public_ip"
          user_name: "opc"
          private_key: "env.TF_VAR_private_key"
          public_key: "env.TF_VAR_public_key"
      file_exists_test_public:
        args:
          public_ip: "output.public_ip"
          file_name: "/etc/nfs.conf,/etc/nfs1.conf"  
          user_name: "opc"
          private_key: "env.TF_VAR_private_key"
          public_key: "env.TF_VAR_public_key"     
      ssh_test_private:
        args:
          public_ip: "output.public_ip"
          private_ip: "output.oci_instances.apache_http_server1.private_ip,output.oci_instances.apache_http_server2.private_ip"
          user_name: "opc"
          private_key: "env.TF_VAR_private_key"
          public_key: "env.TF_VAR_public_key"
      RunShellScriptTestPublic:
        args:
          public_ip: "output.public_ip"
          user_name: "opc"
          script_name: "/Users/vsnaik/terraform/solutions/sdf-oci-sol-httpd/examples/quick-start/test/bastion_test.sh"
          private_key: "env.TF_VAR_private_key"
          public_key: "env.TF_VAR_public_key"     
  #Load Balancer Tests..
  lb:
    output: oci_lb
    terra_checks:
      state: "ACTIVE"
    generic_checks:
      http_status_test_public:
        args:
          url: "http://output.ip_addresses:8080/"
          expected_status: 200
          time_out_in_secs: 10